### ISSUE TITLE
HI i have get this error can you please help me how to solve it

### ISSUE THREAD

**Issue by sajid-desgner** [anil-sidhu/react-ssr-with-routing#2]
PS C:\Users\Sajid\Desktop\gj-eshop-master> node server/index.js
C:\Users\Sajid\Desktop\gj-eshop-master\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:13
    throw new Error(prefix + ": " + (message || ''));
    ^

Error: Invariant failed: Browser history needs a DOM
    at invariant (C:\Users\Sajid\Desktop\gj-eshop-master\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:13:11)
    at createBrowserHistory (C:\Users\Sajid\Desktop\gj-eshop-master\node_modules\history\cjs\history.js:273:16)
    at Object.<anonymous> (C:\Users\Sajid\Desktop\gj-eshop-master\src\/history.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (C:\Users\Sajid\Desktop\gj-eshop-master\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .js] (C:\Users\Sajid\Desktop\gj-eshop-master\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
PS C:\Users\Sajid\Desktop\gj-eshop-master>

**Comment by Sangram9693** [comment]
did you find any solution for this error ?

**Comment by manishjha5410** [comment]
Use ReactDOMServer.renderToNodeStream() instead of ReactDOMServer.renderToString()

**Comment by manishjha5410** [comment]
In server.js
