### ISSUE TITLE
Error: Invariant failed: Browser history needs a DOM

### ISSUE THREAD

**Issue by Sangram9693** [anil-sidhu/react-ssr-with-routing#4]
I am getting below error when i am trying to run localhost:8080.

`Error: Invariant failed: Browser history needs a DOM
    at invariant (D:\sangram\react\ssr-example\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:13:11)
    at Object.createHistory [as createBrowserHistory] (D:\sangram\react\ssr-example\node_modules\history\cjs\history.js:273:16)
    at new BrowserRouter (D:\sangram\react\ssr-example\node_modules\react-router-dom\modules\BrowserRouter.js:11:13)
    at processChild (D:\sangram\react\ssr-example\node_modules\react-dom\cjs\react-dom-server.node.development.js:3161:14)
    at resolve (D:\sangram\react\ssr-example\node_modules\react-dom\cjs\react-dom-server.node.development.js:3126:5)
    at ReactDOMServerRenderer.render (D:\sangram\react\ssr-example\node_modules\react-dom\cjs\react-dom-server.node.development.js:3600:22)
    at ReactDOMServerRenderer.read (D:\sangram\react\ssr-example\node_modules\react-dom\cjs\react-dom-server.node.development.js:3538:29)
    at Object.renderToString (D:\sangram\react\ssr-example\node_modules\react-dom\cjs\react-dom-server.node.development.js:4247:27)
    at D:\sangram\react\ssr-example\server\/server.js:23:42
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)`

**Comment by hasheemismath** [comment]
Use ReactDOMServer.renderToNodeStream() instead of ReactDOMServer.renderToString()

**Comment by Orbis25** [comment]
> Use ReactDOMServer.renderToNodeStream() instead of ReactDOMServer.renderToString()

excelent working for mee!

**Comment by tejasrgaikwad** [comment]
Thanks @hasheemismath  working perfectly!

**Comment by wc-dharmendra** [comment]
<div id="root">[object Object]</div>

Find this issue

**Comment by wc-dharmendra** [comment]
<div id="root">[object Object]</div>

Find this issue in root div port function working fine but View source show only <div id="root">[object Object]</div>  how to resolve this issue

**Comment by manishjha5410** [comment]
Please share your code

**Comment by manishjha5410** [comment]
@wc-dharmendra  please share your code

**Comment by harshidhasiva** [comment]
How to solve above error could you please let me know.

**Comment by VikasTiwari7** [comment]
I also got the 

[object Object]

When i run the local server

Anyone can help me please
