### ISSUE TITLE
How to solve this issues Error: Invariant failed: Browser history needs a DOM

### ISSUE THREAD

**Issue by harshidhasiva** [anil-sidhu/react-ssr-with-routing#9]
Error: Invariant failed: Browser history needs a DOM
    at invariant (F:\react\znap\znapcash\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:13:11)
    at Object.createHistory [as createBrowserHistory] (F:\react\znap\znapcash\node_modules\history\cjs\history.js:273:16)
    at new BrowserRouter (F:\react\znap\znapcash\node_modules\react-router-dom\modules\BrowserRouter.js:11:13)
    at processChild (F:\react\znap\znapcash\node_modules\react-dom\cjs\react-dom-server.node.development.js:3305:14

**Comment by harshidhasiva** [comment]
Hi Anil could you please solve this issue please i struct last two days.. thanks
